inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'spec/factories.rb'

Metrics/LineLength:
  Max: 80
  IgnoredPatterns: ['\A\s*#']

Rails/Output:
  Exclude:
    - 'db/seeds.rb'
