inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

# Exclusions below refer to Rails-generated files
AllCops:
  Exclude:
    - 'bin/*'

Metrics/LineLength:
  Max: 80
  IgnoredPatterns: ['\A\s*#']
  Exclude:
    - 'db/schema.rb'

Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'

